/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import Estructuras.Grafo;
import Estructuras.ListaAdy;

/**
 * Nombre: DetecciónDeComplejosProteicos 
 * Descripcion general: Interfaz grafica (JFrame) que permite visualizar 
 * la deteccion de complejos proteicos mediante 
 * los algoritmos de busqueda BFS (anchura) y DFS (profundidad)
 * Tipo de retorno: void (Clase)
 * @author Daniel Saracual
 * @author Emily Rodriguez
 * @version 1.0
 */
public class DetecciónDeComplejosProteicos extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DetecciónDeComplejosProteicos.class.getName());
    static Grafo g;

    /**
     * Nombre: DetecciónDeComplejosProteicos (Constructor)
     * Descripcion general: Crea e inicializa los componentes de la ventana 
     * recibiendo el grafo actual
     * Tipo de retorno: DetecciónDeComplejosProteicos (Objeto)
     * @param f Tipo: Grafo. Descripcion: el grafo que contiene las proteinas
     * y sus relaciones
     */
    public DetecciónDeComplejosProteicos(Grafo f) {
        initComponents();
        this.g = f;
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jLabel2.setText("Deteccion de Complejos Proteicos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jButton2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton2.setText("BFS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        jButton3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton3.setText("DFS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, 40));

        area.setColumns(20);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 600, 270));

        jButton4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton4.setText("Regresar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Nombre: jButton2ActionPerformed 
     * Descripcion general: Evento ejecutado al presionar el boton "BFS", realiza
     * un recorrido en anchura en el grafo para detectar los complejos 
     * e imprime el resultado en el area de texto 
     * Tipo de retorno: void
     * @param evt Tipo: java.awt.event.ActionEvent. Descripcion: el evento de 
     * accion generado por el boton
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ListaAdy[] recorrido = g.BFS();
        this.area.setText("");
        for (int i = 0; i < recorrido.length; i++) {
            if (recorrido[i] != null) {
                this.area.setText(this.area.getText() + "\n" + recorrido[i].imprimir());
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * Nombre: jButton3ActionPerformed
     * Descripcion general: Evento ejecutado al presionar el boton "DFS", 
     * realiza un recorrido en profundidad en el grafo para detectar los 
     * complejos e imprime el resultado en el area de texto 
     * Tipo de retorno: void
     * @param evt Tipo: java.awt.event.ActionEvent. Descripcion: el evento de 
     * accion generado por el boton
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ListaAdy[] recorrido = g.DFS();
        this.area.setText("");

        for (int i = 0; i < recorrido.length; i++) {
            if (recorrido[i] != null) {
                this.area.setText(this.area.getText() + "\n" + recorrido[i].imprimir());
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * Nombre: jButton4ActionPerformed 
     * Descripcion general: Evento ejecutado al presionar el boton "Regresar", 
     * cierra la ventana actual y muestra el Menu principal
     * Tipo de retorno: void
     * @param evt Tipo: java.awt.event.ActionEvent. Descripcion: el evento de 
     * accion generado por el boton
     */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Menu m = new Menu(g);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * Nombre: main 
     * Descripcion general: Metodo principal que lanza la aplicacion e inicializa
     * el aspecto visual (Look and feel) de la ventana
     * Tipo de retorno: void
     * @param args Tipo: String. Descripcion: argumentos de linea de comandos 
     * enviados al ejecutar
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DetecciónDeComplejosProteicos(g).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
