/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import Estructuras.Grafo;
import javax.swing.JOptionPane;

/**
 * Nombre: ModificarGrafos 
 * Descripcion general: Interfaz grafica (JFrame) que permite al usuario alterar 
 * la estructura del grafo agregando nuevas proteinas, eliminandolas, 
 * o creando nuevas relaciones (aristas) con un peso determinado
 * Tipo de retorno: void (Clase)
 * @author Daniel Saracual
 * @author Emily Rodriguez
 * @version 1.0
 */
public class ModificarGrafos extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ModificarGrafos.class.getName());
    static Grafo g;

    /**
     * Nombre: ModificarGrafos (Constructor) Descripcion general: Crea e inicializa
     * los componentes de la ventana de modificacion, recibiendo y guardando el grafo 
     * a modificar Tipo de retorno: ModificarGrafos (Objeto)
     *
     * @param g Tipo: Grafo. Descripcion: el grafo actual sobre el que se haran 
     * las modificaciones
     */
    public ModificarGrafos(Grafo g) {
        initComponents();
        this.g = g;
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        rel = new javax.swing.JTextField();
        peso = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton3.setText("Agregar proteina ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jLabel3.setText("Modificar grafo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        nombre.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        nombre.setText("Nombre proteína");
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 210, 50));

        jButton4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton4.setText("Agregar proteina ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, 50));

        jButton6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton6.setText("Eliminar proteina");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, -1, 50));

        jButton1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton1.setText("Agregar relación");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, 210, 50));

        rel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        rel.setText("Proteína relación");
        jPanel1.add(rel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 210, 50));

        peso.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        peso.setText("Peso");
        jPanel1.add(peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 210, 50));

        jButton5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton5.setText("Regresar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 660, -1, -1));

        jLabel1.setText("Esta proteína se relacionará con el nombre proteína");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * Nombre: nombreActionPerformed Descripcion general: Evento disparado al
     * realizar una accion sobre el campo de texto del nombre de la proteina
     * Tipo de retorno: void
     *
     * @param evt Descripcion: el evento de accion generado por el campo de texto
     */
    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    /**
     * Nombre: jButton3ActionPerformed 
     * Descripcion general: Evento al presionar el boton  de agregar proteina. 
     * Inserta el vertice y muestra 
     * mensaje 
     * Tipo de retorno: void
     * @param evt Tipo: java.awt.event.ActionEvent. Descripcion: el evento de 
     * accion generado por el boton
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        g.crearproteina(this.nombre.getText());
        JOptionPane.showMessageDialog(rootPane, "Proteina insertada correctamente");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * Nombre: jButton4ActionPerformed 
     * Descripcion general: Evento al presionar el boton "Agregar proteina". 
     * Valida que el nombre no este vacio y que la proteina no exista antes de 
     * insertarla en el grafo
     * Tipo de retorno: void
     * @param evt Tipo: java.awt.event.ActionEvent. Descripcion: el evento de 
     * accion generado por el boton
     */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    String nuevaProteina = nombre.getText().trim();

    if (nuevaProteina.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Error: Debe ingresar un nombre para la proteína.");
    } else {
        if (g.buscar(nuevaProteina) == null) {
            g.crearproteina(nuevaProteina);
            JOptionPane.showMessageDialog(this, "Proteína '" + nuevaProteina + "' insertada correctamente.");
            nombre.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Error: La proteína '" + nuevaProteina + "' ya existe en el grafo.");
        }
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * Nombre: jButton6ActionPerformed 
     * Descripcion general: Evento al presionar el boton "Eliminar proteina".
     * Valida que el campo no este vacio y que el vertice exista antes de removerlo
     * del grafo 
     * Tipo de retorno: void
     * @param evt Tipo: java.awt.event.ActionEvent. Descripcion: el evento de 
     * accion generado por el boton
     */
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    String valor = nombre.getText().trim();

    if (valor.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Error: El campo de texto está vacío.");
    } else {
        if (g.buscar(valor) != null) {
            g.eliminarvertice(valor);
            JOptionPane.showMessageDialog(this, "La proteína '" + valor + "' ha sido eliminada correctamente.");
            nombre.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Error: La proteína '" + valor + "' no existe en el grafo.");
        }
    }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * Nombre: jButton1ActionPerformed 
     * Descripcion general: Evento al presionar el  boton "Agregar relación". 
     * Valida campos vacios, existencia de nodos, y previene ciclos para luego
     * insertar una nueva arista con peso 
     * Tipo de retorno: void
     * @param evt Tipo: java.awt.event.ActionEvent. Descripcion: el evento de
     * accion generado por el boton
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    String p1 = nombre.getText().trim();
    String p2 = rel.getText().trim();
    String pesoTexto = peso.getText().trim();

    if (p1.isEmpty() || p2.isEmpty() || pesoTexto.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Error: Todos los campos son obligatorios.");
        return;
    }

    if (g.buscar(p1) == null || g.buscar(p2) == null) {
        JOptionPane.showMessageDialog(this, "Error: Una o ambas proteínas no existen en el grafo.");
        return;
    }

    if (g.existeArista(p1, p2)) {
        JOptionPane.showMessageDialog(this, "Aviso: Esta relación ya existe en el sistema.");
        return;
    }

    if (p1.equalsIgnoreCase(p2)) {
        JOptionPane.showMessageDialog(this, "Error: No se permite conectar una proteína consigo misma.");
        return;
    }

    try {
        int pesoValor = Integer.parseInt(pesoTexto);
        if (pesoValor < 0) {
            JOptionPane.showMessageDialog(this, "Error: El peso debe ser un número positivo.");
            return;
        }

        g.insertararistas(p1, p2, pesoValor);
        JOptionPane.showMessageDialog(this, "Relación creada con éxito.");
        rel.setText("");
        peso.setText("");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error: El peso debe ser un número entero válido.");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Nombre: jButton5ActionPerformed 
     * Descripcion general: Evento al presionar el boton "Regresar", cierra la 
     * ventana actual de modificacion y vuelve a abrir el Menu principal
     * Tipo de retorno: void
     * @param evt Tipo: java.awt.event.ActionEvent. Descripcion: el evento de 
     * accion generado por el boton
     */
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Menu m = new Menu(g);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * Nombre: main 
     * Descripcion general: Metodo principal que lanza la aplicacion
     * e inicializa el aspecto visual (Look and feel) de la ventana
     * ModificarGrafos
     * Tipo de retorno: void
     *
     * @param args Tipo: String. Descripcion: argumentos de linea de 
     * comandos enviados al ejecutar
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ModificarGrafos(g).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField peso;
    private javax.swing.JTextField rel;
    // End of variables declaration//GEN-END:variables
}
