/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import Estructuras.Grafo;

/**
 * Nombre: RutaCorta Descripcion general: Interfaz grafica (JFrame) que permite 
 * al usuario calcular y visualizar la ruta mas corta (camino minimo) entre dos 
 * proteinas especificas utilizando el algoritmo de Dijkstra Tipo de retorno: void (Clase)
 * @author Daniel Saracual
 * @author Emily Rodriguez
 */
public class RutaCorta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RutaCorta.class.getName());
    static Grafo g;
    /**
     * Nombre: RutaCorta (Constructor) Descripcion general: Crea e inicializa
     * los componentes de la ventana para calcular la ruta mas corta, recibiendo 
     * el grafo con la red de proteinas Tipo de retorno: RutaCorta (Objeto)
     *
     * @param g Descripcion: el grafo actual que contiene los vertices y aristas
     */
    public RutaCorta(Grafo g) {
        initComponents();
                this.g = g;
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        nombre = new javax.swing.JTextField();
        rel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jLabel2.setText("Ruta corta");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        jButton2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton2.setText("Encontrar cadena");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 280, 140));

        jButton3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, -1, -1));

        nombre.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        nombre.setText("Origen");
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 210, -1));

        rel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        rel.setText("Destino");
        jPanel1.add(rel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 210, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Nombre: jButton2ActionPerformed Descripcion general: Evento al presionar
     * el boton "Encontrar cadena", toma el nombre de la proteina de origen y destino,
     * ejecuta el algoritmo de Dijkstra y muestra la ruta y peso total en el area de texto 
     * Tipo de retorno: void
     *
     * @param evt Descripcion: el evento de accion generado por el boton
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.jTextArea1.setText(g.Dijkstra(this.nombre.getText(), this.rel.getText()));
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * Nombre: jButton3ActionPerformed Descripcion general: Evento al presionar el 
     * boton "Regresar", cierra la ventana actual de busqueda de rutas y vuelve 
     * a abrir el Menu principal Tipo de retorno: void
     *
     * @param evt Descripcion: el evento de accion generado por el boton
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Menu m = new Menu(g);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * Nombre: main Descripcion general: Metodo principal que lanza la aplicacion
     * e inicializa el aspecto visual (Look and feel) de la ventana de Ruta Corta
     * Tipo de retorno: void
     *
     * @param args Descripcion: argumentos de linea de comandos enviados al ejecutar
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RutaCorta(g).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField rel;
    // End of variables declaration//GEN-END:variables
}
